sft:
  max_num_epochs: 20
  max_num_steps: 1200
  val_period: 50
  val_batches: 8
  val_global_batch_size: 32
  val_micro_batch_size: 1
  val_at_start: true
  seed: 42
checkpointing:
  enabled: true
  checkpoint_dir: results/sft-qwen3-14b-ss2-delta1
  metric_name: val_loss
  higher_is_better: false
  keep_top_k: 3
  save_period: 50
policy:
  use_lora: true
  model_name: Qwen/Qwen3-14B
  tokenizer:
    name: Qwen/Qwen3-14B
  train_global_batch_size: 32
  train_micro_batch_size: 1
  max_total_sequence_length: 16000
  precision: bfloat16
  fsdp_offload_enabled: false
  activation_checkpointing_enabled: false
  dtensor_cfg:
    enabled: true
    cpu_offload: false
    sequence_parallel: false
    activation_checkpointing: true
    tensor_parallel_size: 1
    custom_parallel_plan: null
  dynamic_batching:
    enabled: False
  make_sequence_length_divisible_by: 1
  max_grad_norm: 1
  optimizer:
    name: torch.optim.AdamW
    kwargs:
      lr: 5e-06
      weight_decay: 0.001
      betas:
        - 0.9
        - 0.98
      eps: 1e-08
      foreach: false
      fused: false
data:
  max_input_seq_length: 16000
  dataset_name: wmt
  add_bos: true
  add_eos: true
  add_generation_prompt: false
  span_type: "none"
  train_file: "../reasoning-mqm/data/da_train_2017-22.jsonl.filt.delta1.0.merged.rand.clean.train"
  val_file: "../reasoning-mqm/data/da_train_2017-22.jsonl.filt.delta1.0.merged.rand.clean.dev"
logger:
  log_dir: logs/sft-qwen3-14b-ss2-delta1-lora
  wandb_enabled: true
  tensorboard_enabled: true
  monitor_gpus: true
  wandb:
    project: ss2
    name: sft-qwen3-14b-ss2-delta1-lora
  tensorboard:
    log_dir: tb_logs-sft-dev-qwen3-14b-ss2-delta1-lora
  gpu_monitoring:
    collection_interval: 10
    flush_interval: 10
cluster:
  gpus_per_node: 1
  num_nodes: 1
